# Generated by Django 4.1.7 on 2023-03-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('flavour', models.CharField(max_length=300)),
                ('prize', models.PositiveIntegerField()),
                ('shape', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('number', models.CharField(max_length=200, unique=True)),
                ('cake_image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
