# Generated by Django 4.1.7 on 2023-03-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='weight',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
